config/routes.rb
Rails.application.routes.draw do
	resources :sessions, only: [:new, :create, :destroy] 
  resources :users
  get 'signup', to: 'users#new', as: 'signup'
  
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

	resources :pics do
		member do
			put "like", to: "pics#upvote"
		end
	end

	root "pics#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic.rb
class Pic < ApplicationRecord
	require 'acts_as_votable'
	
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?

	belongs_to :user
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pics
  attr_accessor :custom_field
  has_secure_password

  validates :first_name,
  					presence: true
  validates :last_name,
  					presence: true
  validates :email,
  					presence: true,
  					uniqueness: true,
  					format: {
  						with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  					}

  def to_s
  	"#{first_name} #{last_name}"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	before_action :find_pic, only: [:show, :destroy, :edit, :update, :upvote]

	def index
		if params[:search]
			@pics = Pic.where('title LIKE ?', "%#{params[:search]}%")
		else
			@pics = Pic.all.order("created_at DESC").page(params[:page]).per_page(3)
		end
	end

	def show
	end

	def new
		if current_user
			@pic = current_user.pics.build
		else
			redirect_to login_path, notice: "Please sign in before posting"
		end
	end

	def create
		@pic = current_user.pics.build(pic_params)
			if @pic.save
				redirect_to @pic, notice: "Created successfully"
			else
				render "new"
			end	
	end

	def edit
	end

	def update
		if @pic.update(pic_params)
			redirect_to @pic, notice: "Updated Pic!"
		else
			render 'edit'
		end
	end

	def destroy
		@pic.destroy
		redirect_to root_path, notice: "Pic Deleted!"
	end

	def upvote
		if current_user
			@pic.upvote_by current_user
			redirect_back fallback_location: root_path
		else
			redirect_to login_path, notice: "Please sign in before upvoting"
		end
	end

	private
		def pic_params
			params.require(:pic).permit(:title, :description, :image, :address, :latitude, :longitude)
		end

		def find_pic
			@pic = Pic.find(params[:id])
		end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to root_path, notice: "Logged in"
  	else
  		render new
  	end
  end

  def destroy
    reset_session
  	session[:user_id] = nil
    current_user = nil
  	redirect_to root_path, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_only!, only: [:index]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end


  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def admin_only!
      unless current_user.admin?
        redirect_to root_path, notice: "You are not allowed there!"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Iinstagram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1 style="display: inline-block;"><%= link_to 'IInstagram', root_path %></h1>
  <div style="display: inline-block; float:right;"><% if current_user %>
    Logged in as <%= current_user.email %>,
    <%= link_to "Profile", user_path(current_user) %>
    <%= link_to "Log Out", logout_path %>
  <% else %>
    <%= link_to "Sign Up", signup_path %> or
    <%= link_to "Log In", login_path %>
  <% end %>
  </div>
  <br>
  <br>
  <br>
  <% flash.each do |name, msg| %>
  	<%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>

    <%= yield %>
  
  </body>
</html>

app/views/pics/_form.html.erb
<%= simple_form_for @pic, html: {multipart: true } do |f| %>
	<% if @pic.errors.any? %>

	<%= pluralize(@pic.errors.count, "error") %>
	prevented this Pic from saving
	<ul>
		<% @pic.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	<% end %>
	</ul>
	
	<%= f.input :title %>
	<%= f.input :image %>
	<%= f.input :description %>
	
	<div class="field">
    <%= f.input :address %>
  </div>

  <div class="field">
    <%= f.input :latitude %><span>(leave empty)</span>
  </div>

  <div class="field">
    <%= f.input :longitude %><span>(leave empty)</span>

	<br>
	<%= f.button :submit %>


<% end %>

app/views/pics/_pic.html.erb
	<%= link_to (image_tag pic.image.url(:medium)), pic %>
	<h2><%= link_to pic.title, pic %></h2>

app/views/pics/edit.html.erb
<h1>Edit pic</h1>

<%= image_tag @pic.image.url(:medium) %>
<%= render 'form' %>
<%= link_to 'Cancel', pic_path %>

app/views/pics/index.html.erb
<div style="text-align:center">

<%= will_paginate @pics %>

	<h2><%= link_to 'Create new pic!', new_pic_path %></h2>
	
	<%= form_tag pics_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  <% end %>
	<div id="pics">
		<%= render @pics %>
	</div>
</div>

app/views/pics/index.js.erb
$('#pics').append('<%= j render(@pics) %>');
<% if @pics.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate(@pics) %>');
<% else %>
	$('.pagination').remove();
<% end %>
<% sleep 1 %>

app/views/pics/new.html.erb
<h1>Post something</h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>

app/views/pics/show.html.erb
<div style="text-align: center;">
<%= image_tag @pic.image.url %>
<h1 ><%= @pic.title %></h1>

<%= @pic.description %>

<p> Posted by: <%= @pic.user.email %> </p>

		<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@pic.latitude}%2C#{@pic.longitude}&key=#{Rails.application.secrets.google_places_key}" %>
<p> Posted at: <%= @pic.address %> </p>

<br>

<br/>
	<%= link_to "Back", root_path %>
	<%= link_to "like", like_pic_path(@pic), method: :put %>
	<%= @pic.get_upvotes.size %>

<% if current_user %>
	<% if current_user == @pic.user || current_user.admin == true %>
		<%= link_to 'Edit', edit_pic_path %>
		<%= link_to 'Delete', pic_path, method: :delete, data: {confirm: "Are you sure?"} %>
	<% end %>
<% end %>
</div>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :admin, :style => "width: 100px;"%>

    
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>